using Microsoft.EntityFrameworkCore;
using System.Collections.Concurrent;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContext<AppDb>(o => o.UseSqlite(builder.Configuration.GetConnectionString("Default")));
builder.Services.AddHttpClient();
builder.Services.AddSingleton<JobQueue>();
builder.Services.AddScoped<AiClient>();
builder.Services.AddScoped<TtsClient>();
builder.Services.AddScoped<NovelProcessor>();
builder.Services.AddHostedService<JobWorker>();
builder.Services.AddCors(o => o.AddDefaultPolicy(p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
var app = builder.Build();
Directory.CreateDirectory("data"); Directory.CreateDirectory("storage/audio"); Directory.CreateDirectory("storage/output");
using (var s = app.Services.CreateScope()){var db=s.ServiceProvider.GetRequiredService<AppDb>();db.Database.EnsureCreated();Seed.Ensure(db);}
app.UseCors();

app.MapGet("/api/novels", async (AppDb db) => await db.Novels.OrderByDescending(x=>x.Id).ToListAsync());
app.MapPost("/api/novels/upload", async (HttpRequest req, AppDb db) => {var form=await req.ReadFormAsync();var file=form.Files["file"]??throw new BadHttpRequestException("file required");using var sr=new StreamReader(file.OpenReadStream());var n=new Novel{Title=form["title"].FirstOrDefault()??Path.GetFileNameWithoutExtension(file.FileName),SourceFile=file.FileName,Content=await sr.ReadToEndAsync()};db.Novels.Add(n);await db.SaveChangesAsync();return Results.Ok(n);});
app.MapGet("/api/novels/{id:long}", async (long id, AppDb db) => {var n=await db.Novels.FindAsync(id);if(n==null)return Results.NotFound();return Results.Ok(new{novel=n,characters=await db.Characters.Where(x=>x.NovelId==id).ToListAsync(),scripts=await db.Scripts.Where(x=>x.NovelId==id).OrderBy(x=>x.Order).ToListAsync()});});
app.MapPost("/api/novels/{id:long}/analyze", async (long id,AppDb db,JobQueue q)=>Results.Ok(await Jobs.Enqueue(db,q,"AnalyzeNovel",JsonSerializer.Serialize(new{novelId=id}))));
app.MapPost("/api/novels/{id:long}/audio", async (long id,AppDb db,JobQueue q)=>Results.Ok(await Jobs.Enqueue(db,q,"GenerateAudio",JsonSerializer.Serialize(new{novelId=id}))));
app.MapPut("/api/characters/{id:long}", async (long id,Character dto,AppDb db)=>{var e=await db.Characters.FindAsync(id);if(e==null)return Results.NotFound();e.Name=dto.Name;e.Gender=dto.Gender;e.Personality=dto.Personality;e.Description=dto.Description;e.VoiceFile=dto.VoiceFile;await db.SaveChangesAsync();return Results.Ok(e);});
app.MapGet("/api/jobs",async(AppDb db)=>await db.Jobs.OrderByDescending(x=>x.Id).Take(200).ToListAsync());
app.MapGet("/api/settings",(AppDb db)=>db.Settings.ToDictionary(x=>x.Key,x=>x.Value));
app.MapPut("/api/settings",async(Dictionary<string,string> data,AppDb db)=>{foreach(var kv in data){var e=await db.Settings.FirstOrDefaultAsync(x=>x.Key==kv.Key);if(e==null)db.Settings.Add(new Setting{Key=kv.Key,Value=kv.Value});else e.Value=kv.Value;}await db.SaveChangesAsync();return Results.Ok();});
app.MapGet("/api/settings/voices",(AppDb db)=>{var dir=Settings.Get(db,"VoiceDirectory","voices");if(!Directory.Exists(dir))return Results.Ok(Array.Empty<object>());return Results.Ok(Directory.EnumerateFiles(dir,"*.wav").Select(x=>new{name=Path.GetFileNameWithoutExtension(x),path=x}));});
app.MapPost("/api/writing/learn/{id:long}",async(long id,AppDb db,AiClient ai)=>{var n=await db.Novels.FindAsync(id);if(n==null)return Results.NotFound();var sample=n.Content[..Math.Min(n.Content.Length,30000)];var summary=await ai.Chat("你是小说写作技法分析专家","分析叙事视角、语言风格、节奏、人物塑造、对白、章节结构、悬念、情绪推进，并形成可复用写作方法：\n"+sample);var st=new WritingStyle{NovelId=id,Name=n.Title+"-写作风格",Summary=summary,PromptTemplate=summary};db.WritingStyles.Add(st);await db.SaveChangesAsync();return Results.Ok(st);});
app.MapGet("/api/writing/styles",async(AppDb db)=>await db.WritingStyles.OrderByDescending(x=>x.Id).ToListAsync());
app.MapPost("/api/writing/generate",async(GenerateRequest r,AppDb db,AiClient ai)=>{var st=r.StyleId is null?null:await db.WritingStyles.FindAsync(r.StyleId);var text=await ai.Chat("你是专业中文小说作者。保持给定写作方法，但生成全新内容。",(st?.PromptTemplate??"")+"\n创作要求："+r.Prompt);var g=new GeneratedNovel{Title=r.Title,StyleId=r.StyleId,SourceNovelId=r.SourceNovelId,Prompt=r.Prompt,Content=text};db.GeneratedNovels.Add(g);await db.SaveChangesAsync();return Results.Ok(g);});
app.MapGet("/api/writing/generated",async(AppDb db)=>await db.GeneratedNovels.OrderByDescending(x=>x.Id).ToListAsync());
app.MapGet("/api/writing/generated/{id:long}/download",async(long id,AppDb db)=>{var g=await db.GeneratedNovels.FindAsync(id);return g==null?Results.NotFound():Results.File(Encoding.UTF8.GetBytes(g.Content),"text/plain",g.Title+".txt");});

app.MapPost("/api/writing/generated/{id:long}/publish",async(long id,AppDb db)=>{var g=await db.GeneratedNovels.FindAsync(id);if(g==null)return Results.NotFound();var n=new Novel{Title=g.Title,SourceFile="AI生成",Content=g.Content,Status="Uploaded"};db.Novels.Add(n);await db.SaveChangesAsync();return Results.Ok(n);});
app.MapGet("/api/jobs/{id:long}/download",async(long id,AppDb db)=>{var j=await db.Jobs.FindAsync(id);if(j?.Result==null||!File.Exists(j.Result))return Results.NotFound();return Results.File(j.Result,"audio/mpeg",Path.GetFileName(j.Result));});
app.Run();

record GenerateRequest(string Title,long? StyleId,long? SourceNovelId,string Prompt);
class AppDb(DbContextOptions<AppDb> o):DbContext(o){public DbSet<Novel> Novels=>Set<Novel>();public DbSet<Character> Characters=>Set<Character>();public DbSet<ScriptLine> Scripts=>Set<ScriptLine>();public DbSet<JobRecord> Jobs=>Set<JobRecord>();public DbSet<Setting> Settings=>Set<Setting>();public DbSet<WritingStyle> WritingStyles=>Set<WritingStyle>();public DbSet<GeneratedNovel> GeneratedNovels=>Set<GeneratedNovel>();protected override void OnModelCreating(ModelBuilder b){b.Entity<Setting>().HasIndex(x=>x.Key).IsUnique();}}
class Novel{public long Id{get;set;}public string Title{get;set;}="";public string SourceFile{get;set;}="";public string Content{get;set;}="";public string Status{get;set;}="Uploaded";public DateTime CreatedAt{get;set;}=DateTime.UtcNow;}
class Character{public long Id{get;set;}public long NovelId{get;set;}public string Name{get;set;}="";public string? Gender{get;set;}public string? Personality{get;set;}public string? Description{get;set;}public string? VoiceFile{get;set;}}
class ScriptLine{public long Id{get;set;}public long NovelId{get;set;}public long? CharacterId{get;set;}public int Order{get;set;}public string Speaker{get;set;}="旁白";public string Text{get;set;}="";public string? Emotion{get;set;}public string? AudioFile{get;set;}public string Status{get;set;}="Pending";}
class JobRecord{public long Id{get;set;}public string Type{get;set;}="";public string Status{get;set;}="Queued";public int Progress{get;set;}public string? Payload{get;set;}public string? Result{get;set;}public string? Error{get;set;}public DateTime CreatedAt{get;set;}=DateTime.UtcNow;}
class Setting{public long Id{get;set;}public string Key{get;set;}="";public string Value{get;set;}="";}
class WritingStyle{public long Id{get;set;}public long? NovelId{get;set;}public string Name{get;set;}="";public string Summary{get;set;}="";public string PromptTemplate{get;set;}="";}
class GeneratedNovel{public long Id{get;set;}public string Title{get;set;}="";public long? SourceNovelId{get;set;}public long? StyleId{get;set;}public string Prompt{get;set;}="";public string Content{get;set;}="";public DateTime CreatedAt{get;set;}=DateTime.UtcNow;}
static class Seed{public static void Ensure(AppDb db){void S(string k,string v){if(!db.Settings.Any(x=>x.Key==k))db.Settings.Add(new Setting{Key=k,Value=v});}S("AiBaseUrl","http://127.0.0.1:8080/v1");S("AiModel","local-model");S("TtsBaseUrl","http://127.0.0.1:7860");S("VoiceDirectory","voices");S("FfmpegPath","ffmpeg");db.SaveChanges();}}
static class Settings{public static string Get(AppDb db,string k,string d)=>db.Settings.FirstOrDefault(x=>x.Key==k)?.Value??d;}
class AiClient(IHttpClientFactory f,AppDb db){public async Task<string> Chat(string system,string prompt,CancellationToken ct=default){var url=Settings.Get(db,"AiBaseUrl","http://127.0.0.1:8080/v1").TrimEnd('/')+"/chat/completions";var model=Settings.Get(db,"AiModel","local-model");using var c=f.CreateClient();var res=await c.PostAsJsonAsync(url,new{model,messages=new[]{new{role="system",content=system},new{role="user",content=prompt}},temperature=.3,stream=false},ct);var body=await res.Content.ReadAsStringAsync(ct);res.EnsureSuccessStatusCode();using var doc=JsonDocument.Parse(body);return doc.RootElement.GetProperty("choices")[0].GetProperty("message").GetProperty("content").GetString()??"";}}
class TtsClient(IHttpClientFactory f,AppDb db){public async Task<string> Generate(string text,string? voice,string output,CancellationToken ct){using var c=f.CreateClient();var url=Settings.Get(db,"TtsBaseUrl","http://127.0.0.1:7860").TrimEnd('/')+"/api/tts";var res=await c.PostAsJsonAsync(url,new{text,ref_audio=voice,language="zh"},ct);if(!res.IsSuccessStatusCode)throw new Exception(await res.Content.ReadAsStringAsync(ct));Directory.CreateDirectory(Path.GetDirectoryName(output)!);await File.WriteAllBytesAsync(output,await res.Content.ReadAsByteArrayAsync(ct),ct);return output;}public async Task<string> Merge(IEnumerable<string> files,string output,CancellationToken ct){var list=Path.ChangeExtension(output,"txt");Directory.CreateDirectory(Path.GetDirectoryName(output)!);await File.WriteAllLinesAsync(list,files.Select(x=>"file '"+Path.GetFullPath(x).Replace("'","'\\''")+"'"),ct);var p=System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(Settings.Get(db,"FfmpegPath","ffmpeg"),"-y -f concat -safe 0 -i \""+list+"\" -c:a libmp3lame -q:a 2 \""+output+"\""){UseShellExecute=false,RedirectStandardError=true,CreateNoWindow=true})!;await p.WaitForExitAsync(ct);if(p.ExitCode!=0)throw new Exception(await p.StandardError.ReadToEndAsync(ct));return output;}}
class NovelProcessor(AppDb db,AiClient ai){public async Task Analyze(long id,JobRecord job,CancellationToken ct){var n=await db.Novels.FindAsync(id)??throw new Exception("Novel not found");var chunks=Enumerable.Range(0,(n.Content.Length+11999)/12000).Select(i=>n.Content.Substring(i*12000,Math.Min(12000,n.Content.Length-i*12000))).ToList();int order=0;for(int ci=0;ci<chunks.Count;ci++){var raw=await ai.Chat("你是专业小说结构分析器，只输出JSON，不要Markdown。","从片段提取人物和逐句朗读脚本。JSON格式:{\"characters\":[{\"name\":\"\",\"gender\":\"\",\"personality\":\"\",\"description\":\"\"}],\"scripts\":[{\"speaker\":\"人物名或旁白\",\"text\":\"\",\"emotion\":\"\"}]}\n"+chunks[ci],ct);raw=raw.Trim();using var doc=JsonDocument.Parse(raw);foreach(var c in doc.RootElement.GetProperty("characters").EnumerateArray()){var name=c.GetProperty("name").GetString()??"";if(name.Length>0&&!db.Characters.Any(x=>x.NovelId==id&&x.Name==name))db.Characters.Add(new Character{NovelId=id,Name=name,Gender=c.TryGetProperty("gender",out var g)?g.GetString():null,Personality=c.TryGetProperty("personality",out var p)?p.GetString():null,Description=c.TryGetProperty("description",out var d)?d.GetString():null});}await db.SaveChangesAsync(ct);foreach(var s in doc.RootElement.GetProperty("scripts").EnumerateArray()){var speaker=s.GetProperty("speaker").GetString()??"旁白";var ch=db.Characters.FirstOrDefault(x=>x.NovelId==id&&x.Name==speaker);db.Scripts.Add(new ScriptLine{NovelId=id,CharacterId=ch?.Id,Order=++order,Speaker=speaker,Text=s.GetProperty("text").GetString()??"",Emotion=s.TryGetProperty("emotion",out var e)?e.GetString():null});}job.Progress=(int)(95.0*(ci+1)/chunks.Count);await db.SaveChangesAsync(ct);}n.Status="Analyzed";job.Progress=100;await db.SaveChangesAsync(ct);}}
record JobMessage(long Id,string Type,string Payload);
class JobQueue{public ConcurrentQueue<JobMessage> Queue{get;}=new();public SemaphoreSlim Signal{get;}=new(0);}
static class Jobs{public static async Task<JobRecord> Enqueue(AppDb db,JobQueue q,string type,string payload){var j=new JobRecord{Type=type,Payload=payload};db.Jobs.Add(j);await db.SaveChangesAsync();q.Queue.Enqueue(new JobMessage(j.Id,type,payload));q.Signal.Release();return j;}}
class JobWorker(IServiceScopeFactory sf,JobQueue q):BackgroundService{protected override async Task ExecuteAsync(CancellationToken ct){while(!ct.IsCancellationRequested){await q.Signal.WaitAsync(ct);if(!q.Queue.TryDequeue(out var m))continue;using var s=sf.CreateScope();var db=s.ServiceProvider.GetRequiredService<AppDb>();var j=await db.Jobs.FindAsync(m.Id);if(j==null)continue;try{j.Status="Running";await db.SaveChangesAsync(ct);var id=JsonDocument.Parse(m.Payload).RootElement.GetProperty("novelId").GetInt64();if(m.Type=="AnalyzeNovel")await s.ServiceProvider.GetRequiredService<NovelProcessor>().Analyze(id,j,ct);else if(m.Type=="GenerateAudio"){var tts=s.ServiceProvider.GetRequiredService<TtsClient>();var lines=await db.Scripts.Where(x=>x.NovelId==id).OrderBy(x=>x.Order).ToListAsync(ct);var files=new List<string>();for(int i=0;i<lines.Count;i++){var x=lines[i];var ch=x.CharacterId==null?null:await db.Characters.FindAsync(x.CharacterId.Value);var file=$"storage/audio/{id}/{x.Order:D6}.wav";await tts.Generate(x.Text,ch?.VoiceFile,file,ct);x.AudioFile=file;x.Status="Completed";files.Add(file);j.Progress=(int)(90.0*(i+1)/Math.Max(lines.Count,1));await db.SaveChangesAsync(ct);}j.Result=await tts.Merge(files,$"storage/output/novel-{id}.mp3",ct);}j.Status="Completed";j.Progress=100;await db.SaveChangesAsync(ct);}catch(Exception ex){j.Status="Failed";j.Error=ex.ToString();await db.SaveChangesAsync(ct);}}}}